### POST request to add new member
POST http://localhost:3000/members
Content-Type: application/json

{
    "name": "Dundee",
    "lastname": "Deemak",
    "position":"Software Developer"
}

### GET request to read members
GET http://localhost:3000/members

### DELETE request to delete a member
DELETE http://localhost:3000/members/1

### PUT requst to update a member
PUT http://localhost:3000/members/1
Content-Type: application/json

{
    "name": "Dundee",
    "lastname": "Deemak",
    "position":"Software Engineer"
}